#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

hsetroot -cover ~/wallpaper.jpg

# bspc config border_width        0
# bspc config window_gap          0

## Nord theme
# Border gaps settings
BW=2
bspc config border_width $BW
bspc config window_gap 4
for side in top right bottom left ; do
    bspc config ${side}_padding $BW
done

# Colors settings
bspc config focused_border_color    "#88C0D0"
bspc config normal_border_color     "#3B4252"
bspc config active_border_color     "#3B4252"
bspc config urgent_border_color     "#EBCB8B"

bspc config split_ratio          0.51
bspc config single_monocle		 true
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
