#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII
bspc monitor HDMI-1 -d VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

polybar example & disown
